FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl

FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl git libc6-dev libssl-dev make build-essential libssl-dev libreadline6-dev zlib1g-dev libyaml-dev

RUN echo "gem: --no-ri --no-rdoc" > /.gemrc
RUN mkdir -p /opt/ruby
RUN git clone https://github.com/sstephenson/ruby-build.git
RUN cd ruby-build && ./install.sh
RUN ruby-build 2.0.0-p247 /opt/ruby
RUN /opt/ruby/bin/gem install bundler

ADD app /opt/app
RUN cd /opt/app && /opt/ruby/bin/bundle install

CMD /opt/ruby/bin/ruby /opt/app/script/rails s
EXPOSE 3000:8080
