FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl
RUN curl -L https://get.rvm.io | bash -s head --ruby=<%= ruby_version %>

ADD /vagrant /opt/<%= app_name %>

RUN /usr/local/rvm/rubies/ruby-2.0.0-p247/bin/bundle

CMD /usr/local/rvm/rubies/ruby-2.0.0-p247/ruby /opt/<%= app_name %>/script/rails s
EXPOSE 3000:8080
